version: "3.8"
services:
  spring-ai-app:
    build: .
    container_name: spring-ai-app
    ports:
      - "8090:8090"
    environment:
      # Bạn có thể khai báo biến môi trường ở đây
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    restart: always
